module.exports = {
  up: queryInterface => {
    return queryInterface.bulkInsert(
      'meetups',
      [
        {
          user_id: 1,
          date: '2019-10-28 18:20:00+00',
          local: 'Rio de Janeiro',
          banner: 1,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Big Data',
          description:
            'Mussum Ipsum, cacilds vidis litro abertis. Quem num gosta di mé, boa gentis num é. Suco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis. Nec orci ornare consequat. Praesent lacinia ultrices consectetur. Sed non ipsum felis.',
        },
        {
          user_id: 2,
          date: '2019-10-28 21:00:00+00',
          local: 'Rio de Janeiro',
          banner: 2,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Cloud Services e AWS',
          description:
            'Nullam volutpat risus nec leo commodo, ut interdum diam laoreet. Sed non consequat odio. Aenean aliquam molestie leo, vitae iaculis nisl. Delegadis gente finis, bibendum egestas augue arcu ut est. Admodum accumsan disputationi eu sit.',
        },
        {
          user_id: 1,
          date: '2019-10-28 18:00:00+00',
          local: 'Rio de Janeiro',
          banner: 3,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Data Science Programming',
          description:
            'Casamentiss faiz malandris se pirulitá. Interagi no mé, cursus quis, vehicula ac nisi. Leite de capivaris, leite de mula manquis sem cabeça. Viva Forevis aptent taciti sociosqu ad litora torquent.',
        },
        {
          user_id: 2,
          date: '2019-10-28 20:00:00+00',
          local: 'Rio de Janeiro',
          banner: 4,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Devops',
          description:
            'Quem num gosta di mim que vai caçá sua turmis! Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose.  Suco de cevadiss deixa as pessoas mais interessantis. Copo furadis é disculpa de bebadis, arcu quam euismod magna.',
        },
        {
          user_id: 1,
          date: '2019-10-28 20:00:00+00',
          local: 'Rio de Janeiro',
          banner: 5,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Dracula Theme',
          description:
            'Sapien in monti palavris qui num significa nadis i pareci latim. A ordem dos tratores não altera o pão duris. Posuere libero varius. Nullam a nisl ut ante blandit hendrerit. Aenean sit amet nisi. Cevadis im ampola pa arma uma pindureta.',
        },
        {
          user_id: 2,
          date: '2019-10-28 17:00:00+00',
          local: 'Rio de Janeiro',
          banner: 6,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Frontend raiz',
          description:
            'Paisis, filhis, espiritis santis. Mauris nec dolor in eros commodo tempor. Aenean aliquam molestie leo, vitae iaculis nisl. In elementis mé pra quem é amistosis quis leo. Não sou faixa preta cumpadi, sou preto inteiris, inteiris.',
        },
        {
          user_id: 1,
          date: '2019-10-28 12:00:00+00',
          local: 'Rio de Janeiro',
          banner: 7,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Gostack Bootcamp - Resenha pós curso',
          description:
            'Quem manda na minha terra sou euzis! Todo mundo vê os porris que eu tomo, mas ninguém vê os tombis que eu levo! Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis. Pra lá , depois divoltis porris, paradis.',
        },
        {
          user_id: 2,
          date: '2019-10-29 14:00:00+00',
          local: 'Rio de Janeiro',
          banner: 8,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Graphs - Node + React',
          description:
            'Si u mundo tá muito paradis? Toma um mé que o mundo vai girarzis! Atirei o pau no gatis, per gatis num morreus. Praesent malesuada urna nisi, quis volutpat erat hendrerit non. Nam vulputate dapibus. Praesent vel viverra nisi.',
        },
        {
          user_id: 1,
          date: '2019-10-29 16:00:00+00',
          local: 'Rio de Janeiro',
          banner: 9,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Macbook Pro Fans',
          description:
            'Manduma pindureta quium dia nois paga. Diuretics paradis num copo é motivis de denguis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Detraxit consequat et quo num tendi nada.',
        },
        {
          user_id: 2,
          date: '2019-10-29 13:00:00+00',
          local: 'Rio de Janeiro',
          banner: 10,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Patterns on React e React Native',
          description:
            'Si num tem leite então bota uma pinga aí cumpadi! Per aumento de cachacis, eu reclamis. Mé faiz elementum girarzis, nisi eros vermeio. Vehicula non. Ut sed ex eros. Vivamus sit amet nibh non tellus tristique interdum.',
        },
        {
          user_id: 1,
          date: '2019-10-29 15:00:00+00',
          local: 'Rio de Janeiro',
          banner: 11,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'PHP e SQL - Ainda estamos aqui',
          description:
            'Leite de capivaris, leite de mula manquis sem cabeça. Suco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose. Mé faiz elementum girarzis, nisi eros vermeio.',
        },
        {
          user_id: 2,
          date: '2019-10-29 10:00:00+00',
          local: 'Rio de Janeiro',
          banner: 12,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Grupo de pessoas diversas tendo uma reunião de negócios',
          description:
            'Aenean aliquam molestie leo, vitae iaculis nisl. Si u mundo tá muito paradis? Toma um mé que o mundo vai girarzis! Quem num gosta di mim que vai caçá sua turmis! Admodum accumsan disputationi eu sit. Vide electram sadipscing et per.',
        },
        {
          user_id: 1,
          date: '2019-11-02 18:20:00+00',
          local: 'Rio de Janeiro',
          banner: 1,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Big Data',
          description:
            'Mussum Ipsum, cacilds vidis litro abertis. Quem num gosta di mé, boa gentis num é. Suco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis. Nec orci ornare consequat. Praesent lacinia ultrices consectetur. Sed non ipsum felis.',
        },
        {
          user_id: 2,
          date: '2019-11-02 21:00:00+00',
          local: 'Rio de Janeiro',
          banner: 2,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Cloud Services e AWS',
          description:
            'Nullam volutpat risus nec leo commodo, ut interdum diam laoreet. Sed non consequat odio. Aenean aliquam molestie leo, vitae iaculis nisl. Delegadis gente finis, bibendum egestas augue arcu ut est. Admodum accumsan disputationi eu sit.',
        },
        {
          user_id: 3,
          date: '2019-11-02 18:00:00+00',
          local: 'Rio de Janeiro',
          banner: 3,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Data Science Programming',
          description:
            'Casamentiss faiz malandris se pirulitá. Interagi no mé, cursus quis, vehicula ac nisi. Leite de capivaris, leite de mula manquis sem cabeça. Viva Forevis aptent taciti sociosqu ad litora torquent.',
        },
        {
          user_id: 4,
          date: '2019-11-02 20:00:00+00',
          local: 'Rio de Janeiro',
          banner: 4,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Devops',
          description:
            'Quem num gosta di mim que vai caçá sua turmis! Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose.  Suco de cevadiss deixa as pessoas mais interessantis. Copo furadis é disculpa de bebadis, arcu quam euismod magna.',
        },
        {
          user_id: 5,
          date: '2019-11-02 20:00:00+00',
          local: 'Rio de Janeiro',
          banner: 5,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Dracula Theme',
          description:
            'Sapien in monti palavris qui num significa nadis i pareci latim. A ordem dos tratores não altera o pão duris. Posuere libero varius. Nullam a nisl ut ante blandit hendrerit. Aenean sit amet nisi. Cevadis im ampola pa arma uma pindureta.',
        },
        {
          user_id: 1,
          date: '2019-11-02 17:00:00+00',
          local: 'Rio de Janeiro',
          banner: 6,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Frontend raiz',
          description:
            'Paisis, filhis, espiritis santis. Mauris nec dolor in eros commodo tempor. Aenean aliquam molestie leo, vitae iaculis nisl. In elementis mé pra quem é amistosis quis leo. Não sou faixa preta cumpadi, sou preto inteiris, inteiris.',
        },
        {
          user_id: 2,
          date: '2019-11-02 12:00:00+00',
          local: 'Rio de Janeiro',
          banner: 7,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Gostack Bootcamp - Resenha pós curso',
          description:
            'Quem manda na minha terra sou euzis! Todo mundo vê os porris que eu tomo, mas ninguém vê os tombis que eu levo! Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis. Pra lá , depois divoltis porris, paradis.',
        },
        {
          user_id: 3,
          date: '2019-11-02 14:00:00+00',
          local: 'Rio de Janeiro',
          banner: 8,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Graphs - Node + React',
          description:
            'Si u mundo tá muito paradis? Toma um mé que o mundo vai girarzis! Atirei o pau no gatis, per gatis num morreus. Praesent malesuada urna nisi, quis volutpat erat hendrerit non. Nam vulputate dapibus. Praesent vel viverra nisi.',
        },
        {
          user_id: 4,
          date: '2019-11-02 16:00:00+00',
          local: 'Rio de Janeiro',
          banner: 9,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Macbook Pro Fans',
          description:
            'Manduma pindureta quium dia nois paga. Diuretics paradis num copo é motivis de denguis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Detraxit consequat et quo num tendi nada.',
        },
        {
          user_id: 5,
          date: '2019-11-02 13:00:00+00',
          local: 'Rio de Janeiro',
          banner: 10,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Patterns on React e React Native',
          description:
            'Si num tem leite então bota uma pinga aí cumpadi! Per aumento de cachacis, eu reclamis. Mé faiz elementum girarzis, nisi eros vermeio. Vehicula non. Ut sed ex eros. Vivamus sit amet nibh non tellus tristique interdum.',
        },
        {
          user_id: 1,
          date: '2019-11-02 15:00:00+00',
          local: 'Rio de Janeiro',
          banner: 11,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'PHP e SQL - Ainda estamos aqui',
          description:
            'Leite de capivaris, leite de mula manquis sem cabeça. Suco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose. Mé faiz elementum girarzis, nisi eros vermeio.',
        },
        {
          user_id: 2,
          date: '2019-11-02 10:00:00+00',
          local: 'Rio de Janeiro',
          banner: 12,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Grupo de pessoas diversas tendo uma reunião de negócios',
          description:
            'Aenean aliquam molestie leo, vitae iaculis nisl. Si u mundo tá muito paradis? Toma um mé que o mundo vai girarzis! Quem num gosta di mim que vai caçá sua turmis! Admodum accumsan disputationi eu sit. Vide electram sadipscing et per.',
        },
        {
          user_id: 1,
          date: '2019-11-02 19:20:00+00',
          local: 'Rio de Janeiro',
          banner: 1,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Big Data',
          description:
            'Mussum Ipsum, cacilds vidis litro abertis. Quem num gosta di mé, boa gentis num é. Suco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis. Nec orci ornare consequat. Praesent lacinia ultrices consectetur. Sed non ipsum felis.',
        },
        {
          user_id: 2,
          date: '2019-11-03 12:20:00+00',
          local: 'Rio de Janeiro',
          banner: 2,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Cloud Services e AWS',
          description:
            'Nullam volutpat risus nec leo commodo, ut interdum diam laoreet. Sed non consequat odio. Aenean aliquam molestie leo, vitae iaculis nisl. Delegadis gente finis, bibendum egestas augue arcu ut est. Admodum accumsan disputationi eu sit.',
        },
        {
          user_id: 3,
          date: '2019-11-03 13:20:00+00',
          local: 'Rio de Janeiro',
          banner: 3,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Data Science Programming',
          description:
            'Casamentiss faiz malandris se pirulitá. Interagi no mé, cursus quis, vehicula ac nisi. Leite de capivaris, leite de mula manquis sem cabeça. Viva Forevis aptent taciti sociosqu ad litora torquent.',
        },
        {
          user_id: 4,
          date: '2019-11-03 14:40:00+00',
          local: 'Rio de Janeiro',
          banner: 4,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Devops',
          description:
            'Quem num gosta di mim que vai caçá sua turmis! Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose.  Suco de cevadiss deixa as pessoas mais interessantis. Copo furadis é disculpa de bebadis, arcu quam euismod magna.',
        },
        {
          user_id: 5,
          date: '2019-11-03 15:20:00+00',
          local: 'Rio de Janeiro',
          banner: 5,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Dracula Theme',
          description:
            'Sapien in monti palavris qui num significa nadis i pareci latim. A ordem dos tratores não altera o pão duris. Posuere libero varius. Nullam a nisl ut ante blandit hendrerit. Aenean sit amet nisi. Cevadis im ampola pa arma uma pindureta.',
        },
        {
          user_id: 1,
          date: '2019-11-04 11:30:00+00',
          local: 'Rio de Janeiro',
          banner: 6,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Frontend raiz',
          description:
            'Paisis, filhis, espiritis santis. Mauris nec dolor in eros commodo tempor. Aenean aliquam molestie leo, vitae iaculis nisl. In elementis mé pra quem é amistosis quis leo. Não sou faixa preta cumpadi, sou preto inteiris, inteiris.',
        },
        {
          user_id: 2,
          date: '2019-11-04 12:40:00+00',
          local: 'Rio de Janeiro',
          banner: 7,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Gostack Bootcamp - Resenha pós curso',
          description:
            'Quem manda na minha terra sou euzis! Todo mundo vê os porris que eu tomo, mas ninguém vê os tombis que eu levo! Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis. Pra lá , depois divoltis porris, paradis.',
        },
        {
          user_id: 3,
          date: '2019-11-04 13:50:00+00',
          local: 'Rio de Janeiro',
          banner: 8,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Graphs - Node + React',
          description:
            'Si u mundo tá muito paradis? Toma um mé que o mundo vai girarzis! Atirei o pau no gatis, per gatis num morreus. Praesent malesuada urna nisi, quis volutpat erat hendrerit non. Nam vulputate dapibus. Praesent vel viverra nisi.',
        },
        {
          user_id: 4,
          date: '2019-11-04 14:10:00+00',
          local: 'Rio de Janeiro',
          banner: 9,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Macbook Pro Fans',
          description:
            'Manduma pindureta quium dia nois paga. Diuretics paradis num copo é motivis de denguis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Detraxit consequat et quo num tendi nada.',
        },
        {
          user_id: 5,
          date: '2019-11-06 15:20:00+00',
          local: 'Rio de Janeiro',
          banner: 10,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Patterns on React e React Native',
          description:
            'Si num tem leite então bota uma pinga aí cumpadi! Per aumento de cachacis, eu reclamis. Mé faiz elementum girarzis, nisi eros vermeio. Vehicula non. Ut sed ex eros. Vivamus sit amet nibh non tellus tristique interdum.',
        },
        {
          user_id: 1,
          date: '2019-11-07 11:50:00+00',
          local: 'Rio de Janeiro',
          banner: 11,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'PHP e SQL - Ainda estamos aqui',
          description:
            'Leite de capivaris, leite de mula manquis sem cabeça. Suco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose. Mé faiz elementum girarzis, nisi eros vermeio.',
        },
        {
          user_id: 2,
          date: '2019-11-08 12:40:00+00',
          local: 'Rio de Janeiro',
          banner: 12,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Grupo de pessoas diversas tendo uma reunião de negócios',
          description:
            'Aenean aliquam molestie leo, vitae iaculis nisl. Si u mundo tá muito paradis? Toma um mé que o mundo vai girarzis! Quem num gosta di mim que vai caçá sua turmis! Admodum accumsan disputationi eu sit. Vide electram sadipscing et per.',
        },
        {
          user_id: 1,
          date: '2019-11-10 08:20:00+00',
          local: 'Rio de Janeiro',
          banner: 1,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Big Data',
          description:
            'Mussum Ipsum, cacilds vidis litro abertis. Quem num gosta di mé, boa gentis num é. Suco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis. Nec orci ornare consequat. Praesent lacinia ultrices consectetur. Sed non ipsum felis.',
        },
        {
          user_id: 2,
          date: '2019-11-10 21:00:00+00',
          local: 'Rio de Janeiro',
          banner: 2,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Cloud Services e AWS',
          description:
            'Nullam volutpat risus nec leo commodo, ut interdum diam laoreet. Sed non consequat odio. Aenean aliquam molestie leo, vitae iaculis nisl. Delegadis gente finis, bibendum egestas augue arcu ut est. Admodum accumsan disputationi eu sit.',
        },
        {
          user_id: 3,
          date: '2019-11-10 18:00:00+00',
          local: 'Rio de Janeiro',
          banner: 3,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Data Science Programming',
          description:
            'Casamentiss faiz malandris se pirulitá. Interagi no mé, cursus quis, vehicula ac nisi. Leite de capivaris, leite de mula manquis sem cabeça. Viva Forevis aptent taciti sociosqu ad litora torquent.',
        },
        {
          user_id: 4,
          date: '2019-11-11 20:00:00+00',
          local: 'Rio de Janeiro',
          banner: 4,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Devops',
          description:
            'Quem num gosta di mim que vai caçá sua turmis! Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose.  Suco de cevadiss deixa as pessoas mais interessantis. Copo furadis é disculpa de bebadis, arcu quam euismod magna.',
        },
        {
          user_id: 5,
          date: '2019-11-12 20:00:00+00',
          local: 'Rio de Janeiro',
          banner: 5,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Dracula Theme',
          description:
            'Sapien in monti palavris qui num significa nadis i pareci latim. A ordem dos tratores não altera o pão duris. Posuere libero varius. Nullam a nisl ut ante blandit hendrerit. Aenean sit amet nisi. Cevadis im ampola pa arma uma pindureta.',
        },
        {
          user_id: 1,
          date: '2019-11-12 17:00:00+00',
          local: 'Rio de Janeiro',
          banner: 6,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Frontend raiz',
          description:
            'Paisis, filhis, espiritis santis. Mauris nec dolor in eros commodo tempor. Aenean aliquam molestie leo, vitae iaculis nisl. In elementis mé pra quem é amistosis quis leo. Não sou faixa preta cumpadi, sou preto inteiris, inteiris.',
        },
        {
          user_id: 2,
          date: '2019-11-13 12:00:00+00',
          local: 'Rio de Janeiro',
          banner: 7,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Gostack Bootcamp - Resenha pós curso',
          description:
            'Quem manda na minha terra sou euzis! Todo mundo vê os porris que eu tomo, mas ninguém vê os tombis que eu levo! Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis. Pra lá , depois divoltis porris, paradis.',
        },
        {
          user_id: 3,
          date: '2019-11-12 14:00:00+00',
          local: 'Rio de Janeiro',
          banner: 8,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Graphs - Node + React',
          description:
            'Si u mundo tá muito paradis? Toma um mé que o mundo vai girarzis! Atirei o pau no gatis, per gatis num morreus. Praesent malesuada urna nisi, quis volutpat erat hendrerit non. Nam vulputate dapibus. Praesent vel viverra nisi.',
        },
        {
          user_id: 4,
          date: '2019-11-15 16:00:00+00',
          local: 'Rio de Janeiro',
          banner: 9,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Macbook Pro Fans',
          description:
            'Manduma pindureta quium dia nois paga. Diuretics paradis num copo é motivis de denguis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Detraxit consequat et quo num tendi nada.',
        },
        {
          user_id: 5,
          date: '2019-11-16 13:00:00+00',
          local: 'Rio de Janeiro',
          banner: 10,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Patterns on React e React Native',
          description:
            'Si num tem leite então bota uma pinga aí cumpadi! Per aumento de cachacis, eu reclamis. Mé faiz elementum girarzis, nisi eros vermeio. Vehicula non. Ut sed ex eros. Vivamus sit amet nibh non tellus tristique interdum.',
        },
        {
          user_id: 2,
          date: '2019-11-17 15:00:00+00',
          local: 'Rio de Janeiro',
          banner: 12,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Grupo de pessoas diversas tendo uma reunião de negócios',
          description:
            'Aenean aliquam molestie leo, vitae iaculis nisl. Si u mundo tá muito paradis? Toma um mé que o mundo vai girarzis! Quem num gosta di mim que vai caçá sua turmis! Admodum accumsan disputationi eu sit. Vide electram sadipscing et per.',
        },
        {
          user_id: 1,
          date: '2019-11-18 10:00:00+00',
          local: 'Rio de Janeiro',
          banner: 11,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'PHP e SQL - Ainda estamos aqui',
          description:
            'Leite de capivaris, leite de mula manquis sem cabeça. Suco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose. Mé faiz elementum girarzis, nisi eros vermeio.',
        },
        {
          user_id: 1,
          date: '2019-11-20 08:20:00+00',
          local: 'Rio de Janeiro',
          banner: 1,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Big Data',
          description:
            'Mussum Ipsum, cacilds vidis litro abertis. Quem num gosta di mé, boa gentis num é. Suco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis. Nec orci ornare consequat. Praesent lacinia ultrices consectetur. Sed non ipsum felis.',
        },
        {
          user_id: 2,
          date: '2019-11-20 21:00:00+00',
          local: 'Rio de Janeiro',
          banner: 2,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Cloud Services e AWS',
          description:
            'Nullam volutpat risus nec leo commodo, ut interdum diam laoreet. Sed non consequat odio. Aenean aliquam molestie leo, vitae iaculis nisl. Delegadis gente finis, bibendum egestas augue arcu ut est. Admodum accumsan disputationi eu sit.',
        },
        {
          user_id: 3,
          date: '2019-11-20 18:00:00+00',
          local: 'Rio de Janeiro',
          banner: 3,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Data Science Programming',
          description:
            'Casamentiss faiz malandris se pirulitá. Interagi no mé, cursus quis, vehicula ac nisi. Leite de capivaris, leite de mula manquis sem cabeça. Viva Forevis aptent taciti sociosqu ad litora torquent.',
        },
        {
          user_id: 4,
          date: '2019-11-21 20:00:00+00',
          local: 'Rio de Janeiro',
          banner: 4,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Devops',
          description:
            'Quem num gosta di mim que vai caçá sua turmis! Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose.  Suco de cevadiss deixa as pessoas mais interessantis. Copo furadis é disculpa de bebadis, arcu quam euismod magna.',
        },
        {
          user_id: 5,
          date: '2019-11-22 20:00:00+00',
          local: 'Rio de Janeiro',
          banner: 5,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Dracula Theme',
          description:
            'Sapien in monti palavris qui num significa nadis i pareci latim. A ordem dos tratores não altera o pão duris. Posuere libero varius. Nullam a nisl ut ante blandit hendrerit. Aenean sit amet nisi. Cevadis im ampola pa arma uma pindureta.',
        },
        {
          user_id: 1,
          date: '2019-11-22 17:00:00+00',
          local: 'Rio de Janeiro',
          banner: 6,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Frontend raiz',
          description:
            'Paisis, filhis, espiritis santis. Mauris nec dolor in eros commodo tempor. Aenean aliquam molestie leo, vitae iaculis nisl. In elementis mé pra quem é amistosis quis leo. Não sou faixa preta cumpadi, sou preto inteiris, inteiris.',
        },
        {
          user_id: 2,
          date: '2019-11-23 12:00:00+00',
          local: 'Rio de Janeiro',
          banner: 7,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Gostack Bootcamp - Resenha pós curso',
          description:
            'Quem manda na minha terra sou euzis! Todo mundo vê os porris que eu tomo, mas ninguém vê os tombis que eu levo! Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis. Pra lá , depois divoltis porris, paradis.',
        },
        {
          user_id: 3,
          date: '2019-11-22 14:00:00+00',
          local: 'Rio de Janeiro',
          banner: 8,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Graphs - Node + React',
          description:
            'Si u mundo tá muito paradis? Toma um mé que o mundo vai girarzis! Atirei o pau no gatis, per gatis num morreus. Praesent malesuada urna nisi, quis volutpat erat hendrerit non. Nam vulputate dapibus. Praesent vel viverra nisi.',
        },
        {
          user_id: 4,
          date: '2019-11-25 16:00:00+00',
          local: 'Rio de Janeiro',
          banner: 9,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Macbook Pro Fans',
          description:
            'Manduma pindureta quium dia nois paga. Diuretics paradis num copo é motivis de denguis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Detraxit consequat et quo num tendi nada.',
        },
        {
          user_id: 5,
          date: '2019-11-26 13:00:00+00',
          local: 'Rio de Janeiro',
          banner: 10,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Patterns on React e React Native',
          description:
            'Si num tem leite então bota uma pinga aí cumpadi! Per aumento de cachacis, eu reclamis. Mé faiz elementum girarzis, nisi eros vermeio. Vehicula non. Ut sed ex eros. Vivamus sit amet nibh non tellus tristique interdum.',
        },
        {
          user_id: 2,
          date: '2019-11-27 15:00:00+00',
          local: 'Rio de Janeiro',
          banner: 12,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Grupo de pessoas diversas tendo uma reunião de negócios',
          description:
            'Aenean aliquam molestie leo, vitae iaculis nisl. Si u mundo tá muito paradis? Toma um mé que o mundo vai girarzis! Quem num gosta di mim que vai caçá sua turmis! Admodum accumsan disputationi eu sit. Vide electram sadipscing et per.',
        },
        {
          user_id: 1,
          date: '2019-11-28 10:00:00+00',
          local: 'Rio de Janeiro',
          banner: 11,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'PHP e SQL - Ainda estamos aqui',
          description:
            'Leite de capivaris, leite de mula manquis sem cabeça. Suco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose. Mé faiz elementum girarzis, nisi eros vermeio.',
        },
        {
          user_id: 1,
          date: '2019-12-10 08:20:00+00',
          local: 'Rio de Janeiro',
          banner: 1,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Big Data',
          description:
            'Mussum Ipsum, cacilds vidis litro abertis. Quem num gosta di mé, boa gentis num é. Suco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis. Nec orci ornare consequat. Praesent lacinia ultrices consectetur. Sed non ipsum felis.',
        },
        {
          user_id: 2,
          date: '2019-12-10 21:00:00+00',
          local: 'Rio de Janeiro',
          banner: 2,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Cloud Services e AWS',
          description:
            'Nullam volutpat risus nec leo commodo, ut interdum diam laoreet. Sed non consequat odio. Aenean aliquam molestie leo, vitae iaculis nisl. Delegadis gente finis, bibendum egestas augue arcu ut est. Admodum accumsan disputationi eu sit.',
        },
        {
          user_id: 3,
          date: '2019-12-10 18:00:00+00',
          local: 'Rio de Janeiro',
          banner: 3,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Data Science Programming',
          description:
            'Casamentiss faiz malandris se pirulitá. Interagi no mé, cursus quis, vehicula ac nisi. Leite de capivaris, leite de mula manquis sem cabeça. Viva Forevis aptent taciti sociosqu ad litora torquent.',
        },
        {
          user_id: 4,
          date: '2019-12-11 20:00:00+00',
          local: 'Rio de Janeiro',
          banner: 4,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Devops',
          description:
            'Quem num gosta di mim que vai caçá sua turmis! Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose.  Suco de cevadiss deixa as pessoas mais interessantis. Copo furadis é disculpa de bebadis, arcu quam euismod magna.',
        },
        {
          user_id: 5,
          date: '2019-12-12 20:00:00+00',
          local: 'Rio de Janeiro',
          banner: 5,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Dracula Theme',
          description:
            'Sapien in monti palavris qui num significa nadis i pareci latim. A ordem dos tratores não altera o pão duris. Posuere libero varius. Nullam a nisl ut ante blandit hendrerit. Aenean sit amet nisi. Cevadis im ampola pa arma uma pindureta.',
        },
        {
          user_id: 1,
          date: '2019-12-12 17:00:00+00',
          local: 'Rio de Janeiro',
          banner: 6,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Frontend raiz',
          description:
            'Paisis, filhis, espiritis santis. Mauris nec dolor in eros commodo tempor. Aenean aliquam molestie leo, vitae iaculis nisl. In elementis mé pra quem é amistosis quis leo. Não sou faixa preta cumpadi, sou preto inteiris, inteiris.',
        },
        {
          user_id: 2,
          date: '2019-12-13 12:00:00+00',
          local: 'Rio de Janeiro',
          banner: 7,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Gostack Bootcamp - Resenha pós curso',
          description:
            'Quem manda na minha terra sou euzis! Todo mundo vê os porris que eu tomo, mas ninguém vê os tombis que eu levo! Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis. Pra lá , depois divoltis porris, paradis.',
        },
        {
          user_id: 3,
          date: '2019-12-12 14:00:00+00',
          local: 'Rio de Janeiro',
          banner: 8,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Graphs - Node + React',
          description:
            'Si u mundo tá muito paradis? Toma um mé que o mundo vai girarzis! Atirei o pau no gatis, per gatis num morreus. Praesent malesuada urna nisi, quis volutpat erat hendrerit non. Nam vulputate dapibus. Praesent vel viverra nisi.',
        },
        {
          user_id: 4,
          date: '2019-12-15 16:00:00+00',
          local: 'Rio de Janeiro',
          banner: 9,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Macbook Pro Fans',
          description:
            'Manduma pindureta quium dia nois paga. Diuretics paradis num copo é motivis de denguis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Detraxit consequat et quo num tendi nada.',
        },
        {
          user_id: 5,
          date: '2019-12-16 13:00:00+00',
          local: 'Rio de Janeiro',
          banner: 10,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Patterns on React e React Native',
          description:
            'Si num tem leite então bota uma pinga aí cumpadi! Per aumento de cachacis, eu reclamis. Mé faiz elementum girarzis, nisi eros vermeio. Vehicula non. Ut sed ex eros. Vivamus sit amet nibh non tellus tristique interdum.',
        },
        {
          user_id: 2,
          date: '2019-12-17 15:00:00+00',
          local: 'Rio de Janeiro',
          banner: 12,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'Grupo de pessoas diversas tendo uma reunião de negócios',
          description:
            'Aenean aliquam molestie leo, vitae iaculis nisl. Si u mundo tá muito paradis? Toma um mé que o mundo vai girarzis! Quem num gosta di mim que vai caçá sua turmis! Admodum accumsan disputationi eu sit. Vide electram sadipscing et per.',
        },
        {
          user_id: 1,
          date: '2019-12-18 10:00:00+00',
          local: 'Rio de Janeiro',
          banner: 11,
          created_at: new Date(),
          updated_at: new Date(),
          title: 'PHP e SQL - Ainda estamos aqui',
          description:
            'Leite de capivaris, leite de mula manquis sem cabeça. Suco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose. Mé faiz elementum girarzis, nisi eros vermeio.',
        },
      ],
      {}
    );
  },

  down: queryInterface => {
    return queryInterface.bulkDelete('meetups', null, {});
  },
};
